Mr15 implement robot upgrading
The-Microservice-Dungeon/robot pull request #11
Opened 2021-11-10 22:28 UTC by Chris-TH

2021-11-13 09:10 UTC, DennisWae commented
Please don't put the code of other tickets into unrelated pull requests, as this makes them harder to review. Please revert your previoues two commits and create new branches for them and open new pull requests.

2021-11-13 09:11 UTC, DennisWae requested changes
Please revert your previous two commits

2021-11-13 17:37 UTC, DennisWae requested changes
Wait until MR8 ist merged into main and then merge main into this branch.

2021-11-13 17:49 UTC, DennisWae commented
MR8 is now merged.

2021-11-18 20:06 UTC, Chris-TH commented
Merged branch 'main' into MR15-Implement-Robot-Upgrading

2021-11-18 21:38 UTC, DennisWae requested changes

2021-11-18 21:38 UTC, DennisWae commented on src/main/kotlin/com/msd/robot/application/RobotApplicationService.kt
> +    }
You need to persist the Robot after modifying it.

2021-11-18 21:54 UTC, DennisWae approved these changes

2021-11-20 12:10 UTC, merged