Health regeneration
The-Microservice-Dungeon/robot pull request #9
Opened 2021-11-08 03:35 UTC by fegbert

Implemented health regeneration

2021-11-08 09:03 UTC, DennisWae commented
You should also write tests for the RobotApplicationService and RobotDomainService, but not implement them yet as someone else shoud do that.

2021-11-08 09:03 UTC, DennisWae requested changes

2021-11-08 09:03 UTC, DennisWae commented on src/main/kotlin/com/msd/robot/domain/Robot.kt
> +    fun regenerateHealth(amount: Int) {
According to the [wiki](https://the-microservice-dungeon.github.io/docs/rules/trading), robots can only be repaired to max health. Also please document your methods.

2021-11-08 09:06 UTC, DennisWae commented on src/main/kotlin/com/msd/robot/domain/Robot.kt
> +    fun regenerateHealth(amount: Int) {
This method should also probably be renamed to `repairRobot`.

2021-11-08 09:18 UTC, baldhat requested changes

2021-11-08 09:18 UTC, baldhat commented on src/main/kotlin/com/msd/robot/domain/Robot.kt
> +        if (amount + this.health > this.maxHealth) throw HealthFullException("Tried to regenerate $amount health but is already at full health.");
The robot should still heal up to its max health. This makes it impossible to heal up to 20, if the robot has 17 Health and tries to heal by 4

2021-11-09 09:50 UTC, DennisWae approved these changes

2021-11-09 16:14 UTC, baldhat approved these changes

2021-11-09 20:49 UTC, merged